addons:
  apt:
    packages:
    - pass
    - gnupg

language: go

go:
  - 1.12.x
  - 1.13.x

env:
  - GO111MODULE=on

script:
  - go test ./...
  - go vet -composites=false ./...
  - make
  - make prove 2>&1
